# Generated by Django 5.2.6 on 2025-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('year_of_study', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('level_of_study', models.CharField(max_length=20)),
                ('exam_type', models.CharField(max_length=25)),
                ('course_title', models.CharField(max_length=250)),
                ('program', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=20)),
                ('collection', models.CharField(blank=True, max_length=100)),
                ('pdf_file', models.FileField(upload_to='exam_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
